### ISSUE TITLE
Ignore/Exclude specific files/glob's from sync

### ISSUE THREAD

**Issue by TruDan** [SimonCropp/GitHubSync#289]
Hi

It would be really useful to me if i could exclude certain files from syncronising. For example we have many microservice API repo's, all of which use a Template Repository to sync common properties/github workflows. for the github workflows specifically is where we have an issue.

Because our template repository has a workflow to sync to all other repo's when changed, this workflow also then gets pushed to all repositories. meaning we need an ugly if repository == 'githubuser/repo' in each action.

What i propose is adding a list property to the configuration like so:

```
templates:
  - name: [template name]
    url: [repository url of the template]
    branch: [branch to use, defaults to `master`]
    exclude:
        - '.github/**/*'
        - 'my_super_secret_file.yml'
    
repositories:
  - name: [repository name]
    url: [repository url of the target repository]
    branch: [target branch, defaults to `master`]
    autoMerge: [true / false, true is only used when user is allowed to merge PRs on the target repository]
    templates:
      - [list of template names to use in the order to apply]
```

I did fork the project and try to add this myself and submit a PR, but i found the code structure very difficult to follow, so perhaps its easier for you to add? It would be really useful though :)
