### ISSUE TITLE
Allow yaml configuration files to drive the sync engine

### ISSUE THREAD

**Issue by GeertvanHorrik** [SimonCropp/GitHubSync#60]
I've written a simple wrapper around this library that creates a configuration similar to the one below:

```
templates:
  - name: geertvanhorrik
    url: https://github.com/geertvanhorrik/repositorytemplate
    branch: master
  - name: catel
    url: https://github.com/Catel/RepositoryTemplate.Components
    branch: master
  - name: wildgums-components-public
    url: https://github.com/wildgums/RepositoryTemplate.Components.Public
    branch: master

repositories:
  - name: CsvHelper
    url: https://github.com/JoshClose/CsvHelper
    branch: master
    autoMerge: false
    templates:
      - geertvanhorrik

  - name: Catel
    url: https://github.com/catel/catel
    branch: develop
    autoMerge: true
    templates:
      - geertvanhorrik
      - catel

  - name: Orc.Controls
    url: https://github.com/wildgums/orc.controls
    branch: develop
    autoMerge: true
    templates:
      - geertvanhorrik
      - wildgums-components-public
```

This way, you can create large lists of synchronizations without having to modify any code. Would you be interested in having this in GitHubSync?
